version: '2'
services:
  db:
    image: mysql
    env_file:
      - MySQL.env
    volumes:
      - ./datadir:/var/lib/mysql
  web:
    build: .
    env_file:
      - MySQL.env
      - Shinobi.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - videos_data:/opt/shinobi/videos
    depends_on:
      - db
    ports:
      - "8081:8080"

volumes:
  videos_data:
    driver: nfs
    driver_opts:
      share: gclee.nas.mlc.app:/cctv-video
